/**
 *
 * $Id$
 */
package fr.obeo.emf.ceson.test.family.validation;

import org.eclipse.emf.common.util.EList;

import fr.obeo.emf.ceson.test.family.Person;

/**
 * A sample validator interface for {@link fr.obeo.emf.ceson.test.family.Family}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FamilyValidator {
	boolean validate();

	boolean validateMembers(EList<Person> value);
}
