/**
 *
 * $Id$
 */
package fr.obeo.emf.ceson.test.family.validation;

import org.eclipse.emf.common.util.EList;

import fr.obeo.emf.ceson.test.family.Child;

/**
 * A sample validator interface for {@link fr.obeo.emf.ceson.test.family.Parent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParentValidator {
	boolean validate();

	boolean validateChildren(EList<Child> value);
}
