/**
 *
 * $Id$
 */
package org.eclipselabs.emf.ceson.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;
import org.eclipselabs.emf.ceson.CDefinition;
import org.eclipselabs.emf.ceson.CValue;

/**
 * A sample validator interface for {@link org.eclipselabs.emf.ceson.CSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CesonSpecificationValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDefinitions(EMap<String, CValue> value);

	boolean validateDefinitions(EList<CDefinition> value);
}
