/**
 *
 * $Id$
 */
package org.eclipselabs.emf.ceson.validation;

import java.math.BigDecimal;

/**
 * A sample validator interface for {@link org.eclipselabs.emf.ceson.CRealValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CRealValueValidator {
	boolean validate();

	boolean validateValue(BigDecimal value);
}
