/**
 *
 * $Id$
 */
package fr.obeo.emf.ceson.validation;

import fr.obeo.emf.ceson.CFeature;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.obeo.emf.ceson.CObjectValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CObjectValueValidator {
	boolean validate();

	boolean validateClassName(String value);
	boolean validateFeatures(EList<CFeature> value);
}
