/**
 *
 * $Id$
 */
package fr.obeo.emf.ceson.validation;

import fr.obeo.emf.ceson.CValue;

import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link fr.obeo.emf.ceson.CSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CSpecificationValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDefinitions(EMap<String, CValue> value);
}
